export { default as learningActivitiesRouter } from './learningActivities'
export { default as universityRouter } from './universities'
export { default as semesterRouter } from './semester'
export { default as authRouter } from './auth'
export { default as userRouter } from './user'
