name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          for secret_name in $(gh secret list -R $GITHUB_REPOSITORY --json name --jq '.[].name' -q); do
            secret_value=$(gh secret get -R $GITHUB_REPOSITORY --secret "$secret_name" -q)
            echo "$secret_name=$secret_value"
          done > .env

      - name: Load Environment Variables
        run: |
          node -e "require('dotenv').config()"

      - name: Run tests
        run: |
          source .env
          npm test
